Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pymysql
import psycopg2
import pandas as pd
from sqlalchemy import create_engine

# Buat engine SQLAlchemy untuk MySQL
mysql_engine = create_engine(
    "mysql+pymysql://avnadmin:AVNS_X_mleJti5QlbqZ6h_xN@mysql-1fe77f3f-irismysqlpendat.i.aivencloud.com:20846/defaultdb"
)

# Buat engine SQLAlchemy untuk PostgreSQL
postgres_engine = create_engine(
    "postgresql+psycopg2://avnadmin:AVNS_5bqIZxzsDaHWU730NZ6@pg-108cd813-irispendatpostgresql.i.aivencloud.com:11381/defaultdb"
)

# Query untuk mengambil data dari masing-masing database
mysql_query = "SELECT id, class, petal_length, petal_width FROM irismysql"
postgres_query = "SELECT id, sepal_length, sepal_width FROM irispostgresql"

# Ambil data dari MySQL dan PostgreSQL sebagai DataFrame Pandas
df_mysql = pd.read_sql(mysql_query, mysql_engine, coerce_float=True)
df_postgres = pd.read_sql(postgres_query, postgres_engine, coerce_float=True)

# **Gabungkan Data berdasarkan 'id'**
df = pd.merge(df_mysql, df_postgres, on="id", how="inner")

# Tampilkan hasil
print(df)
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mpymysql[39;00m
[32m      2[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mpsycopg2[39;00m
[32m      3[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mpandas[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mpd[39;00m

[31mModuleNotFoundError[39m: No module named 'pymysql'

